### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by tb-rules10** [glenndehaan/esports-api#2]
[Link](https://esports.glenndehaan.com/) provided in readme for usage of API is not working.

**Comment by glenndehaan** [comment]
Unfortunately all datasources that I used to collect all the data have vanished. So this API was taken offline 2 years ago.

**Comment by tb-rules10** [comment]
Do you have any other latest esports API project?

**Comment by glenndehaan** [comment]
Unfortunately no, it seems like a lot of service are not exposing the data anymore. Or paywalls have been added.
